# -*- coding: utf-8 -*-
"""graphs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FNP4Esl_VCR3jviE_zdfFUrL9yU5gMl
"""

import matplotlib.pyplot as plt

months = ['Jan', 'Feb', 'Mar', 'Apr', 'May']

company_a = [120, 140, 150, 170, 190]
company_b = [100, 130, 145, 160, 180]

plt.plot(months, company_a, marker='o', label='Company A')
plt.plot(months, company_b, marker='s', label='Company B')

plt.title("Monthly Sales Comparison")
plt.xlabel("Months")
plt.ylabel("Sales")
plt.legend()

plt.show()

from google.colab import drive
drive.mount('/content/drive')

hours=[5,8,4,1,5]
marks=[90,98,70,50,80]
plt.scatter(hours,marks,marker='*',color='red')
plt.xlabel('Hours')
plt.ylabel('Marks')
plt.title('Result of studyed hours')
plt.show()

months = ['Jan', 'Feb', 'Mar', 'Apr', 'May']
sales_2022 = [100, 120, 90, 140, 130]
sales_2023 = [110, 115, 95, 150, 135]
plt.plot(months, sales_2022, marker='*', label='2022')
plt.plot(months, sales_2023, marker='^', label='2023')
plt.xlabel('Month')
plt.ylabel('Sales')
plt.title('Monthly Sales Trend Comparison')
plt.legend()
plt.grid(True)
plt.show()

subjects =['math','science','english','computer']
student1 = [85,75,90,89]
student2 = [70,85,88,80]
#x = np.arange(len(subjects))   # x =4
width =0.35
#print(x -0.175 )
#print(width/2)
plt.bar(subjects,student1,width,label ='Student1')
plt.bar(subjects,student1,width,label ='Student2')
#plt.xticks(x, subjects)
plt.title("Marks Comparison")
plt.xlabel("Subjects")
plt.ylabel("Marks")
plt.legend()

plt.show()

students = ['Alice', 'Bob', 'Charlie', 'David', 'Eva']
marks = [85, 90, 78, 92, 88]
plt.figure(figsize=(8, 5))
plt.plot(students, marks, marker='o', linestyle='-', color='green', linewidth=2)
plt.title('Marks Obtained in Test')
plt.xlabel('Students')
plt.ylabel('Marks')
plt.ylim(0, 100)
plt.show()

products=['Laptop','mobile','keyboard','monitor']
sales=[40000,25000,1200,500]
plt.bar(products,sales)
plt.xlabel("products")
plt.ylabel("sales")
plt.title("Sales of five Products")

plt.show()

tests=['maths','science','English','social','computer']
marks=[85,90,70,90,95]
plt.plot(tests,marks)
plt.xlabel("tests")
plt.ylabel("marks")
plt.title("Marks obtained in five Tests")

plt.show()

